wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1629822206
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 3
      - 8
      4: 3.8.10
      5: 0.12.0
      8:
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 16
dataset:
  desc: null
  value: ImageTagger
epochs:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.01
